apiVersion: v1
kind: Service
metadata:
  name: jwt-generator-svc
  labels:
    app: jwt-generator
spec:
  ports:
  - port: 8080
    targetPort: 9001
  selector:
    app: jwt-generator

---
apiVersion: v1
kind: Service
metadata:
  name: restful-api-svc
  labels:
    app: restful-api
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: restful-api