apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt-generator-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jwt-generator
  template:
    metadata:
      labels:
        app: jwt-generator
    spec:
      containers:
      - name: jwt-generator
        image: soyrodericus/jwtgenerator:IMAGE_REF
        imagePullPolicy: Always
        env:
        - name: mySigningKey
          valueFrom:
            secretKeyRef:
              name: test-env-secret
              key: mySigningKey
        ports:
        - containerPort: 9001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restful-api-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: restful-api
  template:
    metadata:
      labels:
        app: restful-api
    spec:
      containers:
      - name: restful-api
        image: soyrodericus/restfulapi:IMAGE_REF
        imagePullPolicy: Always
        env:
        - name: myAPIKey
          valueFrom:
            secretKeyRef:
              name: test-env-secret
              key: myAPIKey
        - name: mySigningKey
          valueFrom:
            secretKeyRef:
              name: test-env-secret
              key: mySigningKey
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: jwt-generator-svc
  labels:
    app: jwt-generator
spec:
  ports:
  - port: 8080
    targetPort: 9001
  selector:
    app: jwt-generator

---
apiVersion: v1
kind: Service
metadata:
  name: restful-api-svc
  labels:
    app: restful-api
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: restful-api