apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: restfulapi
  namespace: argocd
spec: 
  destination: 
    namespace: default
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: k8s/app
    repoURL: "https://github.com/rcorozo/devops-exercise.git"
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
