name: Build Docker images

on:
  push:
    branches: ['main']
    paths: ['restfulapi/**']

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Get changed files in the restful-api folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files: |
            restful-api/go-rest-api/**
            restful-api/jwt-generator/**
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:restful-api/go-rest-api"
          push: true
          tags: soyrodericus/restfulapi:actions-t1
