name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/login-action@v2
    - name: Login to Docker Hub
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/setup-buildx-action@v2
    - name: Set up Docker Buildx
    - uses: docker/build-push-action@v3
    - name: Build and push
      with:
        context: "{{defaultContext}}:restful-api/go-rest-api"
        push: true
        tags: soyrodericus/restfulapi:actions-t1
