name: Build Docker images

on:
  push:
    branches: ['main']

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub, Set up Docker Buildx, Build and push to hub.docker.com
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        uses: docker/setup-buildx-action@v2
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:restful-api/go-rest-api"
          push: true
          tags: soyrodericus/restfulapi:actions-t1
