name: Install App

on:
  workflow_dispatch:

jobs:
  install-app:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v1
      -
        name: Apply svc
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.base64_KUBE_CONFIG }}
        with:
          args: apply -f k8s/app/svc-api.yaml
      -
        name: Apply deploy
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.base64_KUBE_CONFIG }}
        with:
          args: apply -f k8s/app/deploy-api.yaml