name: Install Argo CD

on:
  workflow_dispatch:

jobs:
  install-argocd:
    runs-on: ubuntu-latest
    steps:
      -
        name: Install Argo CD
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.base64_KUBE_CONFIG }}
        with:
          args: apply -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
      -
        name: Install Argo CD App
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.base64_KUBE_CONFIG }}
        with:
          args: apply -f https://raw.githubusercontent.com/rcorozo/devops-exercise/main/k8s/application.yaml