name: Install NGINX Ingress Controller

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx && helm repo update && helm install ingress-nginx ingress-nginx/ingress-nginx
          kubeconfig: ${{ secrets.plain_KUBE_CONFIG }}
