name: Check k8s connection

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Get nodes to check cluster connection
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get nodes
      -
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx && helm repo update && helm install ingress-nginx ingress-nginx/ingress-nginx
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
