name: Test, Build and Deploy

on:
  workflow_dispatch:
    #branches: ['main']
  push:
    #branches: ['main']
    paths: ['restful-api/**']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - 
        uses: actions/checkout@v3
      - 
        name: restful-api/go-rest-api lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29
          working-directory: restful-api/go-rest-api
        continue-on-error: true
      - 
        name: restful-api/jwt-generator lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29
          working-directory: restful-api/jwt-generator
        continue-on-error: true

  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Get changed files in the restful-api folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files: |
            restful-api/go-rest-api/**
            restful-api/jwt-generator/**
      -
        name: Login to Docker Hub
        #if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        #if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: docker/setup-buildx-action@v2
      -
        name: Create SHORT version of GITHUB_SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      -
        name: Build and push RESTful API Docker image
        #if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:restful-api/go-rest-api"
          push: true
          tags: soyrodericus/restfulapi:${{ github.ref_name }}-${{ steps.vars.outputs.sha_short }}
      -
        name: Build and push JWTGenerator Docker image
        #if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:restful-api/jwt-generator"
          push: true
          tags: soyrodericus/jwtgenerator:${{ github.ref_name }}-${{ steps.vars.outputs.sha_short }}
    outputs:
      imageName: ${{ github.ref_name }}-${{ steps.vars.outputs.sha_short }}
  
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    environment: 
      name: prod
      url: https://restapi.rodrigocorozo.com
    steps:
      -
        name: Deployment update
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          IMAGE_REF: ${{ needs.build.outputs.imageName }}
        with:
          args: envsubst < k8s/01-deployment-restful-api.yaml | kubectl apply -f -